Repository acquia/orca, pull requests merged in 2020-11, with the labels that each got.

#113 Fix project template tests
  src/Domain/Composer/ComposerFacade.php
  tests/Domain/Composer/ComposerFacadeTest.php
Labels: bug

#116 Add support for PHPUnit 9 in Drupal 9.1
  .travis.yml
  src/Domain/Fixture/FixtureCreator.php
Labels: bug, enhancement

#117 Replace PHPStan with drupal-check for deprecation testing
  .idea/php.xml
  composer.json
  composer.lock
  resources/phpstan.neon
  src/Console/Command/Qa/QaDeprecatedCodeScanCommand.php
  src/Domain/Fixture/FixtureCreator.php
  src/Domain/Tool/DrupalCheckTool.php
  src/Helper/Log/TelemetryEventPropertiesBuilder.php
  tests/Console/Command/Qa/QaDeprecatedCodeScanCommandTest.php
  tests/Domain/Tool/DrupalCheckToolTest.php
Labels: breaking, enhancement
