Repository acquia/orca, pull requests merged in 2021-02, with the labels that each got.

#136 Fix INTEGRATED_TEST_ON_CURRENT_DEV failures
  src/Domain/Composer/Version/VersionSelectorFactory.php
  tests/Domain/Composer/Version/VersionSelectorFactoryTest.php
Labels: bug

#130 Fix command not found error in before_cache.sh
  bin/travis/before_cache.sh
Labels: bug

#132 Add acquia/drupal-environment-detector to packages
  config/packages.yml
Labels: enhancement

#138 Update Composer libraries
  composer.json
  composer.lock
Labels: dependencies
