Repository acquia/orca, pull requests merged in 2022-01, with the labels that each got.

#190 ORCA-301: There is no LTS
  bin/ci/_includes.sh
  src/Domain/Ci/Job/Helper/RedundantJobChecker.php
  src/Domain/Ci/Job/IntegratedTestOnLatestLtsCiJob.php
  src/Domain/Composer/Version/DrupalCoreVersionResolver.php
  src/Domain/Composer/Version/DrupalDotOrgApiClient.php
  tests/Domain/Ci/Job/IntegratedTestOnLatestLtsCiJobTest.php
  tests/Domain/Composer/Version/DrupalCoreVersionResolverTest.php
Labels: bug

#192 Apply Composer library security update
  .idea/orca.iml
  composer.json
  composer.lock
Labels: dependencies

#194 [ORCA-291] : Make Nightwatch tests more resilient
  bin/ci/_includes.sh
  example/.travis.yml
Labels: bug

#197 Modifying LTS calculation
  src/Domain/Composer/Version/DrupalCoreVersionResolver.php
  src/Domain/Composer/Version/DrupalDotOrgApiClient.php
  tests/Domain/Composer/Version/DrupalCoreVersionResolverTest.php
Labels: enhancement
