Repository acquia/orca, pull requests merged in 2024-07, with the labels that each got.

#587 Fix drupal-spec-tool version
  config/packages.yml
Labels: chore

#589 Bump Content hub to 3.5.x for all versions of Drupal
  config/packages.yml
Labels: chore

#590 Add Mautic in D10 and remove from D11
  config/packages.yml
Labels: chore

#593 Make live tests required to pass
  bin/ci/self-test/_includes.sh
Labels: enhancement

#591 DRP: Modifications required to make ORCA immune to DRP new release
  src/Options/FixtureOptions.php
  tests/Options/FixtureOptionsTest.php
Labels: dependencies

#595 Use Content Hub dev for dev fixtures
  config/packages.yml
Labels: chore

#596 Content Hub version fixes
  config/packages.yml
Labels: chore

#598 Revert "Use Content Hub dev for dev fixtures"
  config/packages.yml
Labels: chore

#600 Remove Content Hub to prevent upcoming outages
  config/packages.yml
Labels: chore

#601 Remove Media Acquia Dam from D11 fixtures
  config/packages.yml
Labels: chore

#599 Add ORCA_PHPUNIT_DEBUG_MODE_ENABLE variable
  config/services.yml
  src/Domain/Tool/Phpunit/PhpUnitTask.php
  src/Enum/EnvVarEnum.php
Labels: enhancement
