Repository acquia/orca, pull requests merged in 2024-09, with the labels that each got.

#612 Point to DRP 3
  src/Options/FixtureOptions.php
Labels: dependencies

#609 put back acquia dam for d11 tests
  config/packages.yml
Labels: chore

#615 change chrome driver version
  .github/workflows/orca.yml
Labels: enhancement
